import React, { useState } from 'react';
import ImmersiveView from '../ImmersiveView';
import { ExperienceItem } from '../../types';

const proofOfWorkItems: ExperienceItem[] = [
  {
    title: 'Echoes of Tomorrow AI Guide',
    category: 'Museum Event',
    description: 'An AI-driven narrative guide for a speculative futures exhibit, personalizing the visitor experience in real-time.',
    imageUrl: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    metrics: [{label: 'Avg. Engagement', value: '+21 min'}, {label: 'Visitor Return Rate', value: '+12%'}]
  },
  {
    title: 'Generative Art Festival',
    category: 'Live Event',
    description: 'An immersive festival showcasing surreal landscapes generated by AI, with live music and artist talks.',
    imageUrl: 'https://images.pexels.com/photos/2387793/pexels-photo-2387793.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    metrics: [{label: 'Total Attendees', value: '1.2k+'}, {label: 'Peak Viewership', value: '+7.5k'}]
  },
  {
    title: 'Kinetic Forms Interactive Installation',
    category: 'Art Installation',
    description: 'Dynamic, interactive digital sculptures that respond to viewer presence and movement, creating a living art piece.',
    imageUrl: 'https://images.pexels.com/photos/1578332/pexels-photo-1578332.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    metrics: [{label: 'Peak Concurrent Users', value: '250+'}, {label: 'Dwell Time', value: '25 min'}]
  },
];

interface ProofOfWorkPageProps {
  isLoggedIn: boolean;
}

const ProofOfWorkPage: React.FC<ProofOfWorkPageProps> = ({ isLoggedIn }) => {
  const [immersiveItem, setImmersiveItem] = useState<ExperienceItem | null>(null);

  return (
    <div className="container mx-auto text-center animate-fade-in px-4 w-full">
      <h2 className="text-4xl md:text-5xl font-extrabold text-gray-900 dark:text-white mb-4" style={{ textShadow: '0 0 15px rgba(255, 255, 255, 0.2)' }}>
        Experience Gallery
      </h2>
      <p className="text-lg text-gray-700 dark:text-gray-300 max-w-2xl mx-auto mb-12">
        A look back at our greatest hits. Explore interactive showcases of past events and collaborations.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-7xl mx-auto">
        {proofOfWorkItems.map((item) => (
           <div 
            key={item.title} 
            className="flex flex-col group bg-white/60 dark:bg-black/40 backdrop-blur-md rounded-xl border border-gray-200 dark:border-gray-700/50 shadow-lg overflow-hidden transition-all duration-300 hover:border-sky-500/50 hover:shadow-2xl hover:shadow-sky-500/10 transform hover:-translate-y-2"
          >
            <div className="relative">
              <img src={item.imageUrl} alt={item.title} className="w-full h-48 object-cover transition-transform duration-300 group-hover:scale-110" />
              <div className="absolute top-3 right-3 bg-black/50 text-white text-xs font-bold uppercase tracking-wider px-3 py-1 rounded-full">{item.category}</div>
            </div>
            <div className="p-6 text-left flex flex-col flex-grow">
              <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">{item.title}</h3>
              <p className="text-gray-600 dark:text-gray-400 flex-grow mb-4">{item.description}</p>
              
              <div className="border-t border-dashed border-gray-300 dark:border-gray-700 my-4"></div>
              
              <div className="space-y-2 mb-6">
                {item.metrics?.map(metric => (
                    <div key={metric.label} className="flex justify-between items-baseline">
                        <span className="text-sm text-gray-500 dark:text-gray-400">{metric.label}</span>
                        <span className="text-lg font-bold text-lime-600 dark:text-lime-300 font-mono">{metric.value}</span>
                    </div>
                ))}
              </div>

              <div className="flex justify-end items-center mt-auto">
                 <button
                    onClick={() => setImmersiveItem(item)}
                    disabled={!isLoggedIn}
                    className="font-semibold bg-sky-500 text-white px-6 py-2.5 rounded-md hover:bg-sky-400 transition-colors duration-300 transform hover:scale-105 disabled:bg-gray-400 dark:disabled:bg-gray-600 disabled:cursor-not-allowed disabled:transform-none"
                    aria-label={`Launch Demo for ${item.title}`}
                  >
                    View Highlight Reel
                  </button>
              </div>
               {!isLoggedIn && <p className="text-xs text-gray-500 text-right mt-2">You must be logged in to view highlights.</p>}
            </div>
          </div>
        ))}
      </div>
      {immersiveItem && (
        <ImmersiveView 
            item={immersiveItem}
            onExit={() => setImmersiveItem(null)}
        />
      )}
    </div>
  );
};

export default ProofOfWorkPage;